version: "3.9"

services:
  social_service_db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: social
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - social_service_db_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - personalcook_net

  social_service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:postgres@social_service_db:5432/social
      JWT_SECRET: ${JWT_SECRET}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      RECIPE_SERVICE_URL: http://recipe_service:8000/recipes
      USER_SERVICE_URL: http://user_service:8000/users
    depends_on:
      - social_service_db
    ports:
      - "8003:8000"
    networks:
      - personalcook_net

volumes:
  social_service_db_data:

networks:
  personalcook_net:
    external: true
    name: personalcook-net
